paths:
  project_root: "./"
  data_dir: "data"
  raw_data_dir: "data/raw"
  interim_data_dir: "data/interim"
  processed_data_dir: "data/processed"
  external_data_dir: "data/external"
  models_dir: "models"
  cls_model_dir: "models/CLS"
  clsx_model_dir: "models/CLSX"
  reports_dir: "reports"
  figures_dir: "reports/figures"

data:
  train_file: "train.csv"
  test_file: "test.csv"
  val_file: "val.csv"
  sample_submission_file: "sample_submission.csv"
  test_labels_file: "test_labels.csv"
  train_split: 0.8
  random_state: 42

experiment:
  model_architectures:
    - baseline_cls
    - cls_with_additional_tokens
  batch_size: 16
  learning_rate: 0.00005
  num_epochs: 10
  max_seq_length: 256
  tokenizer_name: "xlm-roberta-base"
  seed: 42

model:
  pretrained_model_name: "xlm-roberta-base"
  hidden_size: 768
  num_classes: 6

logging:
  experiment_tracker: "tensorboard"
  log_dir: "logs"
  save_logs_to_repo: false
